package com.entity;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String brandAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String brandName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.type_id
     *
     * @return the value of brand.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.type_id
     *
     * @param typeId the value for brand.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_address
     *
     * @return the value of brand.brand_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getBrandAddress() {
        return brandAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_address
     *
     * @param brandAddress the value for brand.brand_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setBrandAddress(String brandAddress) {
        this.brandAddress = brandAddress == null ? null : brandAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_name
     *
     * @return the value of brand.brand_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_name
     *
     * @param brandName the value for brand.brand_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }
}