package com.entity;

import java.util.Date;

public class Details {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.details_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer detailsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.family_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String familyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.nationality
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.birthday
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.phone
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.email
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.details_id
     *
     * @return the value of details.details_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getDetailsId() {
        return detailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.details_id
     *
     * @param detailsId the value for details.details_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setDetailsId(Integer detailsId) {
        this.detailsId = detailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.user_id
     *
     * @return the value of details.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.user_id
     *
     * @param userId the value for details.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.family_name
     *
     * @return the value of details.family_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.family_name
     *
     * @param familyName the value for details.family_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.name
     *
     * @return the value of details.name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.name
     *
     * @param name the value for details.name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.nationality
     *
     * @return the value of details.nationality
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.nationality
     *
     * @param nationality the value for details.nationality
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.birthday
     *
     * @return the value of details.birthday
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.birthday
     *
     * @param birthday the value for details.birthday
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.phone
     *
     * @return the value of details.phone
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.phone
     *
     * @param phone the value for details.phone
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.email
     *
     * @return the value of details.email
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.email
     *
     * @param email the value for details.email
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}