package com.entity;

public class PawnCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_cart.id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_cart.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_cart.pro_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_cart.price
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Double price;
    private int proNumber;

    public int getProNumber() {
        return proNumber;
    }

    public void setProNumber(int proNumber) {
        this.proNumber = proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_cart.id
     *
     * @return the value of pawn_cart.id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_cart.id
     *
     * @param id the value for pawn_cart.id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_cart.user_id
     *
     * @return the value of pawn_cart.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_cart.user_id
     *
     * @param userId the value for pawn_cart.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_cart.pro_id
     *
     * @return the value of pawn_cart.pro_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_cart.pro_id
     *
     * @param proId the value for pawn_cart.pro_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_cart.price
     *
     * @return the value of pawn_cart.price
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_cart.price
     *
     * @param price the value for pawn_cart.price
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}