package com.entity;

public class PawnAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.account_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.card_no
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.coupon
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String coupon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.account_id
     *
     * @return the value of pawn_account.account_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.account_id
     *
     * @param accountId the value for pawn_account.account_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.user_id
     *
     * @return the value of pawn_account.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.user_id
     *
     * @param userId the value for pawn_account.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.card_no
     *
     * @return the value of pawn_account.card_no
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.card_no
     *
     * @param cardNo the value for pawn_account.card_no
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.coupon
     *
     * @return the value of pawn_account.coupon
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.coupon
     *
     * @param coupon the value for pawn_account.coupon
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setCoupon(String coupon) {
        this.coupon = coupon == null ? null : coupon.trim();
    }
}