package com.entity;

public class PawnAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.account_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.user_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.total_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    private Double totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.usable_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    private Double usableMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_account.wait_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    private Double waitMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.account_id
     *
     * @return the value of pawn_account.account_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.account_id
     *
     * @param accountId the value for pawn_account.account_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.user_id
     *
     * @return the value of pawn_account.user_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.user_id
     *
     * @param userId the value for pawn_account.user_id
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.total_money
     *
     * @return the value of pawn_account.total_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public Double getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.total_money
     *
     * @param totalMoney the value for pawn_account.total_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.usable_money
     *
     * @return the value of pawn_account.usable_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public Double getUsableMoney() {
        return usableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.usable_money
     *
     * @param usableMoney the value for pawn_account.usable_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public void setUsableMoney(Double usableMoney) {
        this.usableMoney = usableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_account.wait_money
     *
     * @return the value of pawn_account.wait_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public Double getWaitMoney() {
        return waitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_account.wait_money
     *
     * @param waitMoney the value for pawn_account.wait_money
     *
     * @mbggenerated Sun Apr 21 15:17:17 CST 2019
     */
    public void setWaitMoney(Double waitMoney) {
        this.waitMoney = waitMoney;
    }
}