package com.entity;

import java.util.Date;

public class PawnUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.username
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.password
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.mobile
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.create_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.role_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.sex
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_user.last_login_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.user_id
     *
     * @return the value of pawn_user.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.user_id
     *
     * @param userId the value for pawn_user.user_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.username
     *
     * @return the value of pawn_user.username
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.username
     *
     * @param username the value for pawn_user.username
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.password
     *
     * @return the value of pawn_user.password
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.password
     *
     * @param password the value for pawn_user.password
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.mobile
     *
     * @return the value of pawn_user.mobile
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.mobile
     *
     * @param mobile the value for pawn_user.mobile
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.create_time
     *
     * @return the value of pawn_user.create_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.create_time
     *
     * @param createTime the value for pawn_user.create_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.role_id
     *
     * @return the value of pawn_user.role_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.role_id
     *
     * @param roleId the value for pawn_user.role_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.sex
     *
     * @return the value of pawn_user.sex
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.sex
     *
     * @param sex the value for pawn_user.sex
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_user.last_login_time
     *
     * @return the value of pawn_user.last_login_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_user.last_login_time
     *
     * @param lastLoginTime the value for pawn_user.last_login_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}