package com.entity;

import java.util.Date;

public class PawnOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_time
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Date orderTime;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_ref
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private String orderRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.address_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    private Integer addressId;

    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_id
     *
     * @return the value of pawn_order.order_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_id
     *
     * @param orderId the value for pawn_order.order_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.user_id
     *
     * @return the value of pawn_order.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.user_id
     *
     * @param userId the value for pawn_order.user_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_time
     *
     * @return the value of pawn_order.order_time
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_time
     *
     * @param orderTime the value for pawn_order.order_time
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_ref
     *
     * @return the value of pawn_order.order_ref
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public String getOrderRef() {
        return orderRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_ref
     *
     * @param orderRef the value for pawn_order.order_ref
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setOrderRef(String orderRef) {
        this.orderRef = orderRef == null ? null : orderRef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.address_id
     *
     * @return the value of pawn_order.address_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.address_id
     *
     * @param addressId the value for pawn_order.address_id
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
}