package com.entity;

import java.util.Date;

public class PawnOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.number
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.pay_status
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.order_ref
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String orderRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.address_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.membership_discount
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Double membershipDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.points
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pawn_order.pay
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer pay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_id
     *
     * @return the value of pawn_order.order_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_id
     *
     * @param orderId the value for pawn_order.order_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.pro_id
     *
     * @return the value of pawn_order.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.pro_id
     *
     * @param proId the value for pawn_order.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.price
     *
     * @return the value of pawn_order.price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.price
     *
     * @param price the value for pawn_order.price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.number
     *
     * @return the value of pawn_order.number
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.number
     *
     * @param number the value for pawn_order.number
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_time
     *
     * @return the value of pawn_order.order_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_time
     *
     * @param orderTime the value for pawn_order.order_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.pay_status
     *
     * @return the value of pawn_order.pay_status
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.pay_status
     *
     * @param payStatus the value for pawn_order.pay_status
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.order_ref
     *
     * @return the value of pawn_order.order_ref
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getOrderRef() {
        return orderRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.order_ref
     *
     * @param orderRef the value for pawn_order.order_ref
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setOrderRef(String orderRef) {
        this.orderRef = orderRef == null ? null : orderRef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.address_id
     *
     * @return the value of pawn_order.address_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.address_id
     *
     * @param addressId the value for pawn_order.address_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.membership_discount
     *
     * @return the value of pawn_order.membership_discount
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Double getMembershipDiscount() {
        return membershipDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.membership_discount
     *
     * @param membershipDiscount the value for pawn_order.membership_discount
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setMembershipDiscount(Double membershipDiscount) {
        this.membershipDiscount = membershipDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.points
     *
     * @return the value of pawn_order.points
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.points
     *
     * @param points the value for pawn_order.points
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pawn_order.pay
     *
     * @return the value of pawn_order.pay
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pawn_order.pay
     *
     * @param pay the value for pawn_order.pay
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }
}