package com.entity;

import java.util.Date;

public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.model
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.peak_price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Double peakPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.creation_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.release_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.products_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String productsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.page_view
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer pageView;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.pro_id
     *
     * @return the value of products.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.pro_id
     *
     * @param proId the value for products.pro_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.brand_id
     *
     * @return the value of products.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.brand_id
     *
     * @param brandId the value for products.brand_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.model
     *
     * @return the value of products.model
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.model
     *
     * @param model the value for products.model
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.peak_price
     *
     * @return the value of products.peak_price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Double getPeakPrice() {
        return peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.peak_price
     *
     * @param peakPrice the value for products.peak_price
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPeakPrice(Double peakPrice) {
        this.peakPrice = peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.creation_time
     *
     * @return the value of products.creation_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.creation_time
     *
     * @param creationTime the value for products.creation_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.release_time
     *
     * @return the value of products.release_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.release_time
     *
     * @param releaseTime the value for products.release_time
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.products_address
     *
     * @return the value of products.products_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getProductsAddress() {
        return productsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.products_address
     *
     * @param productsAddress the value for products.products_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setProductsAddress(String productsAddress) {
        this.productsAddress = productsAddress == null ? null : productsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.page_view
     *
     * @return the value of products.page_view
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getPageView() {
        return pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.page_view
     *
     * @param pageView the value for products.page_view
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setPageView(Integer pageView) {
        this.pageView = pageView;
    }
}