package com.entity;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String typeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_id
     *
     * @return the value of type.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_id
     *
     * @param typeId the value for type.type_id
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_address
     *
     * @return the value of type.type_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getTypeAddress() {
        return typeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_address
     *
     * @param typeAddress the value for type.type_address
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setTypeAddress(String typeAddress) {
        this.typeAddress = typeAddress == null ? null : typeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_name
     *
     * @return the value of type.type_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_name
     *
     * @param typeName the value for type.type_name
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}