package com.mapper;

import com.entity.PawnAccount;
import com.entity.PawnAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PawnAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int countByExample(PawnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int deleteByExample(PawnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int insert(PawnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int insertSelective(PawnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    List<PawnAccount> selectByExample(PawnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    PawnAccount selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") PawnAccount record, @Param("example") PawnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByExample(@Param("record") PawnAccount record, @Param("example") PawnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByPrimaryKeySelective(PawnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_account
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByPrimaryKey(PawnAccount record);
}