package com.mapper;

import com.entity.PawnCart;
import com.entity.PawnCartExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface PawnCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int countByExample(PawnCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int deleteByExample(PawnCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int insert(PawnCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int insertSelective(PawnCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    List<PawnCart> selectByExample(PawnCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    PawnCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") PawnCart record, @Param("example") PawnCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByExample(@Param("record") PawnCart record, @Param("example") PawnCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByPrimaryKeySelective(PawnCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_cart
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByPrimaryKey(PawnCart record);

    List<Map<String,Object>> findProByUserId(Integer userId);

    int updateCartByNumber(PawnCart pawnCart);
}