package com.mapper;

import com.entity.PawnUser;
import com.entity.PawnUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PawnUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int countByExample(PawnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int deleteByExample(PawnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int insert(PawnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int insertSelective(PawnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    List<PawnUser> selectByExample(PawnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    PawnUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") PawnUser record, @Param("example") PawnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByExample(@Param("record") PawnUser record, @Param("example") PawnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByPrimaryKeySelective(PawnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_user
     *
     * @mbggenerated Mon Apr 08 22:05:46 CST 2019
     */
    int updateByPrimaryKey(PawnUser record);
}