package com.mapper;

import com.entity.PawnOrder;
import com.entity.PawnOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface PawnOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int countByExample(PawnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int deleteByExample(PawnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int insert(PawnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int insertSelective(PawnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    List<PawnOrder> selectByExample(PawnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    PawnOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") PawnOrder record, @Param("example") PawnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByExample(@Param("record") PawnOrder record, @Param("example") PawnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByPrimaryKeySelective(PawnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pawn_order
     *
     * @mbggenerated Thu Apr 11 10:45:53 CST 2019
     */
    int updateByPrimaryKey(PawnOrder record);

    List<Map<String,Object>> findOrderByUserId(Integer userId);
    int selectOrderUnfinished();
    int selectOrderAccomplish();
    List<PawnOrder> findOrderUnfinishedList();
    List<PawnOrder> findOrderAccomplishList();
}